# Dockerfile (Flask App)
FROM python:3.9-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Instalar dependências do sistema necessárias para mysqlclient
RUN apt-get update && apt-get install -y \
    gcc \
    libmariadb-dev \
    libmariadb-dev-compat \
    pkg-config \
    && apt-get clean

# Copia o arquivo de requisitos e instala as dependências do Python
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante da aplicação para o container
COPY . .

# Exponha a porta do Flask
EXPOSE 5000

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]
