version: '3.7'

services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile_flask
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: school_db
    ports:
      - "3306:3306"  # Expondo a porta 3306 do container para a 3306 da máquina host
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    depends_on:
      - flask

  mysqld_exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "flask_user:flask_password@(mariadb:3306)/school_db"
    depends_on:
      - mariadb

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile_grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app_network

  tests:
    build:
      context: ./flask
      dockerfile: Dockerfile_flask
    command: pytest /app/test_app.py
    depends_on:
      - mariadb
      - flask

networks:
  app_network:
    driver: bridge
