# Dockerfile (Aplicação Flask AppBuilder)
FROM python:3.9-alpine

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Copiar o arquivo de dependências para o container
COPY requirements.txt ./

# Instala as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o arquivo principal da aplicação
COPY app.py ./

# Adicionar um pequeno atraso antes de iniciar a aplicação Flask
CMD ["sh", "-c", "sleep 15 && python -m flask run --host=0.0.0.0"]
